title = "勇気"
baseURL = "https://starliiit.github.io"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Like tears in rain. Time to die."
  facebook = ""
  twitter = "https://twitter.com/sl_esueru"
  instagram = ""
  youtube = ""
  github = "https://github.com/starliiit"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/under_the_overpass.jpg"
  recent_posts_number = 2
  custom_css = [ "css/custom.css" ]
